<?php


namespace Classes;


class ActivityView extends ActivityContr
{

    public function createActivity(string $activityName, string $activityType, string $activityResourceId, string $activityOwnerId) :bool {

            $this->setCActivityId();
            $this->setCActivityName($activityName);
            $this->setCActivityOwner($activityOwnerId);
            $this->setCActivityResourceId($activityResourceId);
            $this->setCActivityType($activityType);
            return self::createActivityStatus();
    }

    public function getOwnerActivity(string $activityOwnerId): bool|array
    {
            $this->setCActivityOwner($activityOwnerId);
        return parent::getOwnerActivityStatus(); // TODO: Change the autogenerated stub
    }

    public function getActivityOnUserItemsClaimed(string $activityOwnerId): bool|array
    {
        $this->setCActivityOwner($activityOwnerId);
        return parent::getActivityOnUserItemsClaimedStatus(); // TODO: Change the autogenerated stub
    }

    protected function getActivityOnUserItemLikes(string $activityOwnerId): bool|array
    {
        $this->setCActivityOwner($activityOwnerId);
        return parent::getActivityOnUserItemLikesStatus(); // TODO: Change the autogenerated stub
    }


}

