<?php


namespace Classes;


class ApplicationView extends ApplicationContr
{
    public function createApplication(string $applicantId): bool
    {
        $this->setCApplicantId($applicantId);
        return parent::createApplicationStatus(); // TODO: Change the autogenerated stub
    }
}