<?php

namespace Classes;

use DateTime;

class EpisodeContr extends Episode
{

    protected function setCEpisodeId(): void
    {
        $episodeId = Utilities::genUniqueId("eps");
        parent::setEpisodeId($episodeId);
    }

    protected function setCEpisodeDescription(string $episodeDescription): void
    {
        $episodeDescription = Utilities::cleanData($episodeDescription);
        parent::setEpisodeDescription($episodeDescription);
    }

    protected function setCEpisodeDirector(string $episodeDirector): void
    {
        $episodeDirector = Utilities::cleanData($episodeDirector);
        parent::setEpisodeDirector($episodeDirector);
    }
    protected function setCEpisodeDuration(int $episodeDuration): void
    {
        $episodeDuration = Utilities::cleanData($episodeDuration);
        parent::setEpisodeDuration($episodeDuration);
    }

    protected function setCEpisodeLargeArtCover(string $episodeLargeArtCover): void
    {
        $episodeLargeArtCover = Utilities::cleanData($episodeLargeArtCover);
        parent::setEpisodeLargeArtCover($episodeLargeArtCover);
    }

    protected function setCEpisodeName(string $episodeName): void
    {
        $episodeName = Utilities::cleanData($episodeName);
        parent::setEpisodeName($episodeName);
    }

    protected function setCEpisodeNumberInSeries(int $episodeNumberInSeries): void
    {
        $episodeNumberInSeries = Utilities::cleanData($episodeNumberInSeries);
        parent::setEpisodeNumberInSeries($episodeNumberInSeries);
    }

    protected function setCEpisodePremieredCountry(string $episodePremieredCountry): void
    {
        $episodePremieredCountry = Utilities::cleanData($episodePremieredCountry);
        parent::setEpisodePremieredCountry($episodePremieredCountry);
    }

    protected function setCEpisodeSeriesId(string $episodeSeriesId): void
    {
        $episodeSeriesId = Utilities::cleanData($episodeSeriesId);
        parent::setEpisodeSeriesId($episodeSeriesId);
    }

    protected function setCEpisodeSmallArtCover(string $episodeSmallArtCover): void
    {
        $episodeSmallArtCover = Utilities::cleanData($episodeSmallArtCover);
        parent::setEpisodeSmallArtCover($episodeSmallArtCover);
    }

    protected function setCEpisodeStoryline(string $episodeStoryline): void
    {
        $episodeStoryline = Utilities::cleanData($episodeStoryline);
        parent::setEpisodeStoryline($episodeStoryline);
    }
    protected function setCEpisodeUrl(string $episodeUrl): void
    {
        $episodeUrl = Utilities::cleanData($episodeUrl);
        parent::setEpisodeUrl($episodeUrl);
    }
    protected function setCEpisodePremieredDate(DateTime $episodePremieredDate): void
    {
        parent::setEpisodePremieredDate($episodePremieredDate); // TODO: Change the autogenerated stub
    }

    protected function setCEpisodeActorsImages(string $episodeActorsImages): void
    {
        $episodeActorsImages = Utilities::cleanData($episodeActorsImages);
        parent::setEpisodeActorsImages($episodeActorsImages); // TODO: Change the autogenerated stub
    }

    protected function setCEpisodeRating(string $episodeRating): void
    {
        $episodeRating = Utilities::cleanData($episodeRating);
        parent::setEpisodeRating($episodeRating); // TODO: Change the autogenerated stub
    }

}