<?php

namespace Classes;

use DateTime;

class EpisodeView extends EpisodeContr
{

    public function createEpisode(
                    String $episodeSeriesId,
                    String $episodeNumberInSeries,
                    String $episodeName,
                    String $episodeRating,
                    DateTime $episodePremieredDate,
                    int $episodeDuration,
                    String $episodeSmallArtCover,
                    String $episodeLargeArtCover,
                    String $episodeDescription,
                    String $episodeActorsImages,
                    String $episodeDirector,
                    String $episodeUrl,
                    String $episodePremieredCountry,
                    String $episodeStoryline
    ): bool

    {
        $this->setCEpisodeId();
        $this->setCEpisodeRating($episodeRating);
        $this->setCEpisodePremieredDate($episodePremieredDate);
            $this->setCEpisodeActorsImages($episodeActorsImages);
        $this->setCEpisodeSeriesId($episodeSeriesId);
        $this->setCEpisodeUrl($episodeUrl);
        $this->setCEpisodeStoryline($episodeStoryline);
        $this->setCEpisodeNumberInSeries($episodeNumberInSeries);
        $this->setCEpisodeSmallArtCover($episodeSmallArtCover);
        $this->setCEpisodePremieredCountry($episodePremieredCountry);
        $this->setCEpisodeName($episodeName);
        $this->setCEpisodeLargeArtCover($episodeLargeArtCover);
        $this->setCEpisodeDuration($episodeDuration);
        $this->setCEpisodeDirector($episodeDirector);
        $this->setCEpisodeDescription($episodeDescription);
        return parent::createEpisodeResult(); // TODO: Change the autogenerated stub
    }

}