<?php


namespace Classes;


class RewardView extends RewardContr
{

    public function addReward(string $dispatcherId, string $rewardItemId, float $rewardAmount, string $rewardDetails): bool
    {
        $this->setCRewardId();
        $this->setCRewardAmount($rewardAmount);
        $this->setCRewardItemId($rewardItemId);
        $this->setCRewardDispatcherId($dispatcherId);

        return $this->createRewardStatus();
    }

    public function updateReward(string $dispatcherId, string $rewardItemId, float $rewardAmount, string $rewardDetails):bool {

        $this->setCRewardAmount($rewardAmount);
        $this->setCRewardItemId($rewardItemId);
        $this->setCRewardDispatcherId($dispatcherId);

        return $this->updateRewardStatus();
    }

    public function getAllRewards(): null|array
    {
        return parent::getAllRewardsStatus(); // TODO: Change the autogenerated stub
    }

    public function getClaimedRewards(): null|array
    {
        return parent::getClaimedRewardsStatus(); // TODO: Change the autogenerated stub
    }

    public function getUnclaimedRewards(): null|array
    {
        return parent::getUnclaimedRewardsStatus(); // TODO: Change the autogenerated stub
    }

}