<?php


namespace Classes;


class UserView extends UserContr
{
    public function getUser($id): ?array
    {
        $this->addUserId($id);
        return $this->getUserResult();
    }

    public function getAgents(): ?array
    {
        return $this->getAgentsResult();
    }

    public function addAdminEarnings($earnings): bool {
        $this->setCAdminEarnings($earnings);
        return parent::addAdminEarningsStatus();
    }

    public function addUserEarnings(float $earnings,  string $userid): bool {

        $this->setCEarnings($earnings);
        $this->addUserId($userid);

        return parent::addUserEarningsStatus();
    }

    public function updateUser(
        string $firstname,
        string $lastname,
        string $userEmail,
        string $userDoB,
        string $userImage,
        string $oldImage,
        $tempimage,
        string $userPhone,
        string $userBuilding,
        string $userFloor,
        string $userStreet,
        string $userTown,
        string $userCountry,
        string $userBio,
        string $userLinkedIn,
        string $userFacebook
    ): bool
    {

        Utilities::deletePhoto($oldImage, "use");
        $uImage = Utilities::uploadPhoto($userImage, $tempimage, "use");
        if (!$uImage) {
            $uImage = $userImage;
        }

        $this->setCFirstname($firstname);
        $this->setCLastname($lastname);
        $this->setCEmail($userEmail);
        $this->setCUserDoB($userDoB);
        $this->setCUserPhone($userPhone);
        $this->setCUserImage($uImage);
        $this->setCUserBuilding($userBuilding);
        $this->setCUserFloor($userFloor);
        $this->setCUserStreet($userStreet);
        $this->setCUserTown($userTown);
        $this->setCUserCountry($userCountry);
        $this->setCUserBio($userBio);
        $this->setCUserLinkedIn($userLinkedIn);
        $this->setCUserFacebook($userFacebook);

        return $this->updateUserStatus();
    }

    public function checkUsername(string $username): bool
    {
        parent::setCUsername($username);
        return parent::checkUsernameStatus();
    }

    public function checkEmail(string $email): bool
    {
        parent::setCEmail($email);
        return parent::checkEmailStatus();

    }

    public function updatePassword(string $oldPassword, string $newPassword, $userId): bool
    {
        $this->addUserId($userId);
        $this->setCUserOldPassword($oldPassword);
        $this->setCNewPassword($newPassword);
        return parent::updatePasswordStatus();
    }


    public function getAllUsers(): ?array
    {
        return parent::getAllUsersResult();
    }

    public function getAllAgents(): ?array
    {
        return parent::getAllAgentsResult(); // TODO: Change the autogenerated stub
    }

    public function getAllGeneralUsers(): ?array
    {
        return parent::getAllGeneralUsersResult(); // TODO: Change the autogenerated stub
    }

    public function disableUser(string $userId): bool {

        $this->addUserId($userId);
        return parent::disableUserStatus();
    }

}